import Link from 'next/link';
import type { ReactNode } from 'react';

export function PublicBrand() {
  return <Link href="/" aria-label="Investment Planner home" className="inline-flex items-center gap-3 font-bold leading-5 tracking-tight text-slate-950"><span className="grid h-11 w-11 place-items-center rounded-full bg-gradient-to-br from-sky-400 to-blue-600 text-white shadow-lg shadow-blue-500/15"><svg viewBox="0 0 24 24" className="h-7 w-7" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d="M5 19 18 6M8 16C3 8 14 9 19 4c1 8-3 15-11 12Z" /></svg></span><span>Investment<br />Planner</span></Link>;
}

export const authInput = 'mt-2 block h-12 w-full rounded-xl border border-slate-200 bg-white px-4 text-sm text-slate-950 outline-none placeholder:text-slate-400 focus:border-blue-500 disabled:opacity-60';
export const authButton = 'flex min-h-12 w-full items-center justify-center rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white shadow-sm shadow-blue-600/20 hover:bg-blue-700 disabled:cursor-wait disabled:opacity-60';

export function AuthFrame({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: ReactNode }) {
  return <main className="min-h-screen bg-[#f3f8ff] text-slate-900"><div className="mx-auto grid min-h-screen max-w-[1600px] lg:grid-cols-2">
    <section className="relative hidden overflow-hidden border-r border-blue-100 bg-[#e8f2ff] p-12 lg:flex lg:flex-col xl:p-16"><div className="absolute inset-0 bg-[url('/images/dashboard-mountains.png')] bg-cover bg-center opacity-55" /><div className="absolute inset-0 bg-gradient-to-b from-[#edf6ff] via-[#edf6ff]/70 to-white/20" /><div className="relative"><PublicBrand /></div><div className="relative my-auto max-w-lg py-20"><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">A clearer financial picture</p><h2 className="mt-5 text-5xl font-bold leading-[1.12] tracking-tight text-slate-950">Make a plan.<br />See what’s possible.</h2><p className="mt-6 max-w-sm text-lg leading-8 text-slate-600">Your contributions, account room, and long-term projections. Together in one calm, organized space.</p><div className="mt-9 inline-flex items-center gap-3 rounded-2xl border border-white/80 bg-white/85 p-4 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-full bg-emerald-50 text-emerald-600" aria-hidden="true">✓</span><span className="text-sm"><b className="block text-slate-900">A plan that moves with you</b><span className="text-slate-500">Start simple. Adjust as life changes.</span></span></div></div><p className="relative text-xs text-slate-600">A planning tool, not a brokerage or financial adviser.</p></section>
    <section className="flex min-w-0 flex-col px-6 py-8 sm:px-12 lg:px-16"><div className="lg:hidden"><PublicBrand /></div><Link href="/" className="mb-8 hidden self-start text-sm text-slate-500 hover:text-blue-600 lg:block">← Back to home</Link><div className="mx-auto my-auto w-full max-w-[410px] py-12"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">{eyebrow}</p><h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">{title}</h1><p className="mt-3 text-sm leading-6 text-slate-500">{description}</p><div className="mt-8">{children}</div></div><p className="text-center text-xs leading-5 text-slate-500">Investment Planner · Built around your plan</p></section>
  </div></main>;
}
