import Link from 'next/link';
import { PublicBrand } from '@/components/public/auth-frame';

export default function Home() {
  return <div className="min-h-screen overflow-hidden bg-[#f5f9ff] text-slate-900">
    <header className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-6 py-6 lg:px-10"><PublicBrand /><nav aria-label="Public navigation" className="flex items-center gap-4 text-sm font-semibold sm:gap-7"><a href="#features" className="hidden text-slate-500 hover:text-blue-600 sm:block">Features</a><Link href="/login" className="text-slate-600 hover:text-blue-600">Sign in</Link><Link href="/login?mode=signup" className="rounded-xl bg-blue-600 px-4 py-3 text-white hover:bg-blue-700">Get started</Link></nav></header>
    <main>
      <section className="relative mx-auto grid max-w-7xl items-center gap-12 px-6 pb-20 pt-12 lg:grid-cols-[1.05fr_1fr] lg:px-10 lg:pb-28 lg:pt-20"><div className="relative z-10"><p className="inline-flex items-center gap-2 rounded-full border border-blue-100 bg-white px-3 py-1.5 text-xs font-semibold text-blue-700"><span className="h-1.5 w-1.5 rounded-full bg-blue-500" />Your money. A clearer direction.</p><h1 className="mt-6 max-w-xl text-5xl font-bold leading-[1.08] tracking-tight text-slate-950 sm:text-6xl">Plan today.<br /><span className="text-blue-600">See your tomorrow.</span></h1><p className="mt-6 max-w-lg text-lg leading-8 text-slate-500">Bring your monthly plan, TFSA and RRSP contribution room, and investments into one place. Turn the numbers into a plan you can follow.</p><div className="mt-8 flex flex-wrap items-center gap-4"><Link href="/login?mode=signup" className="rounded-xl bg-blue-600 px-6 py-3.5 text-sm font-semibold text-white shadow-lg shadow-blue-600/15 hover:bg-blue-700">Create your plan →</Link><a href="#how-it-works" className="rounded-xl border border-blue-100 bg-white px-6 py-3.5 text-sm font-semibold text-slate-700 hover:border-blue-300">See how it works</a></div><p className="mt-5 text-xs text-slate-500">Manual tracking. No brokerage connection required.</p></div>
      <div className="relative min-w-0"><div className="pointer-events-none absolute -inset-16 rounded-full bg-blue-200/30 blur-3xl" /><div className="relative overflow-hidden rounded-3xl border border-white bg-white/90 p-4 shadow-[0_24px_80px_-25px_#8bb4ee] sm:p-6"><div className="flex items-center justify-between text-xs"><span className="font-semibold text-slate-600">Your financial overview</span><span className="rounded-full bg-slate-100 px-2 py-1 text-slate-500">Illustrative preview</span></div><div className="mt-5 rounded-2xl bg-[#edf5ff] bg-[url('/images/dashboard-mountains.png')] bg-cover bg-center p-5"><p className="text-xs font-semibold uppercase tracking-widest text-blue-700">Small steps. Long-term thinking.</p><h2 className="mt-2 text-2xl font-bold text-slate-950">Your next chapter starts here.</h2></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl border border-slate-100 p-4"><p className="text-xs text-slate-500">Monthly plan</p><p className="mt-2 text-2xl font-bold text-slate-950">$1,000</p><p className="mt-1 text-xs text-slate-400">Allocated with intention</p></div><div className="rounded-xl border border-slate-100 p-4"><p className="text-xs text-slate-500">One clear view</p><p className="mt-2 text-2xl font-bold text-slate-950">3 accounts</p><p className="mt-1 text-xs text-slate-400">TFSA · RRSP · Cash</p></div></div><div className="mt-4 rounded-xl border border-slate-100 p-4"><h3 className="text-sm font-semibold">Give every dollar a direction</h3><div className="mt-4 space-y-4">{[{name:'TFSA',value:600,pct:60,color:'bg-blue-500'},{name:'RRSP',value:250,pct:25,color:'bg-orange-400'},{name:'Cash',value:150,pct:15,color:'bg-emerald-400'}].map(item=><div key={item.name} className="grid grid-cols-[48px_1fr_48px] items-center gap-3 text-xs"><span className="font-medium">{item.name}</span><div><b className="mb-1 block">${item.value}</b><div className="h-2 rounded-full bg-slate-100"><div className={`h-full rounded-full ${item.color}`} style={{width:`${item.pct}%`}} /></div></div><span className="text-right text-slate-500">{item.pct}%</span></div>)}</div></div><p className="mt-4 text-center text-[11px] text-slate-400">Example only. Your plan uses the numbers you enter.</p></div></div></section>
      <section id="features" className="border-y border-blue-100/60 bg-white/70"><div className="mx-auto max-w-7xl px-6 py-16 lg:px-10"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Less scattered. More connected.</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-950">The pieces of your plan, together.</h2><div className="mt-9 grid gap-6 md:grid-cols-3">{[{icon:'↗',title:'A monthly plan that makes sense',copy:'Set percentage allocations across TFSA, RRSP, and cash. See what they mean in dollars.'},{icon:'◉',title:'Know your contribution runway',copy:'Record contributions, track the available room you enter, and explore when your plan could use it up.'},{icon:'⌁',title:'Explore the bigger picture',copy:'Change your time horizon and return assumptions to compare possible outcomes—not promises.'}].map(feature=><article key={feature.title} className="rounded-2xl border border-slate-100 bg-white p-6"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-2xl text-blue-600" aria-hidden="true">{feature.icon}</span><h3 className="mt-5 text-lg font-semibold text-slate-950">{feature.title}</h3><p className="mt-3 text-sm leading-7 text-slate-500">{feature.copy}</p></article>)}</div></div></section>
      <section id="how-it-works" className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><div className="grid gap-10 lg:grid-cols-[1fr_1.4fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Start with what you know</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-950">A little clarity.<br />A practical next step.</h2></div><ol className="grid gap-7 sm:grid-cols-3">{[['Set your baseline','Enter income, expenses, and verified contribution room.'],['Build your plan','Choose how to divide your monthly surplus.'],['Keep it up to date','Log real contributions and update your holdings as you go.']].map(([title,copy],i)=><li key={title}><span className="grid h-9 w-9 place-items-center rounded-full border border-blue-200 bg-white text-sm font-bold text-blue-600">{i+1}</span><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{copy}</p></li>)}</ol></div></section>
      <section className="mx-auto mb-16 max-w-7xl px-6 lg:px-10"><div className="rounded-3xl border border-blue-100 bg-blue-50 px-6 py-12 text-center"><h2 className="text-3xl font-bold tracking-tight text-slate-950">Make room for your future.</h2><p className="mt-3 text-sm text-slate-500">Start with a simple plan. Refine it as you go.</p><Link href="/login?mode=signup" className="mt-6 inline-flex rounded-xl bg-blue-600 px-6 py-3 text-sm font-semibold text-white hover:bg-blue-700">Get started →</Link></div></section>
    </main><footer className="mx-auto flex max-w-7xl flex-col justify-between gap-5 border-t border-blue-100 px-6 py-8 text-xs text-slate-500 sm:flex-row lg:px-10"><span>Investment Planner</span><p className="max-w-lg leading-5">For planning and tracking only. Projections are illustrative, not guaranteed returns. Verify contribution room against your own records.</p><Link href="/login" className="font-semibold text-blue-600">Sign in →</Link></footer>
  </div>;
}
