'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Area, CartesianGrid, ComposedChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { HoldingsForm } from '@/components/forms/holdings-form';
import { formatCAD, formatPct } from '@/lib/format';
import { AppIcon, type AppIconName } from '@/components/ui/app-icon';
import type { HoldingWithInstrument, InstrumentRow } from '@/lib/db/queries';
type Quote={price:number;currency:string;asOf?:string}; type Contribution={id:number;account:string;amount:number;date:string};
const COLORS=['#2563EB','#FB923C','#22C55E','#8B5CF6'];
export function PortfolioClient({userId,instruments,initialHoldings,initialQuotes,contributions}:{userId:string;instruments:InstrumentRow[];initialHoldings:HoldingWithInstrument[];initialQuotes:Record<string,Quote>;contributions:Contribution[]}) {
 const [holdings,setHoldings]=useState(initialHoldings),[quotes,setQuotes]=useState(initialQuotes),[manage,setManage]=useState(false); const tickers=useMemo(()=>[...new Set(holdings.map(h=>h.ticker).filter(Boolean))],[holdings]);
 useEffect(()=>{if(!tickers.length)return;let off=false;fetch(`/api/market/quotes?tickers=${tickers.join(',')}`).then(r=>r.ok?r.json():null).then(d=>{if(!off&&d?.quotes)setQuotes(d.quotes)}).catch(()=>undefined);return()=>{off=true}},[tickers]);
 const openHoldings = () => { setManage(true); window.setTimeout(() => { const editor = document.getElementById('holding-editor'); editor?.scrollIntoView({behavior:'smooth',block:'start'}); editor?.querySelector<HTMLInputElement>('input')?.focus({preventScroll:true}); }, 0); };
 useEffect(() => { const open = () => { if (window.location.hash === '#holding-editor') openHoldings(); }; open(); window.addEventListener('hashchange', open); return () => window.removeEventListener('hashchange', open); }, []);
 const value=(h:HoldingWithInstrument)=>{const q=quotes[h.ticker];const native=q&&h.units>0?h.units*q.price:h.balance_native;return h.currency==='USD'?native*h.fx_rate:native}; const total=holdings.reduce((s,h)=>s+value(h),0);
 const assets=useMemo(()=>Object.entries(holdings.reduce<Record<string,{value:number,name:string}>>((a,h)=>{const k=h.ticker||h.name; a[k]={value:(a[k]?.value||0)+value(h),name:h.name||k};return a},{})).sort((a,b)=>b[1].value-a[1].value).map(([key,item],i)=>({...item,key,color:COLORS[i%COLORS.length]})),[holdings,quotes]);
 const historical: {year:number;value:number}[]=[];
 const returnKnown=false; const activity=contributions.slice(-5).reverse();
 return <div className="mx-auto w-full max-w-[1276px]"><header><h1 className="text-[28px] font-bold tracking-tight">Portfolio</h1><p className="mt-1 text-sm text-[var(--text-muted)]">Your holdings, performance, and asset allocation.</p></header>
 <section className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{([{icon:'briefcase',label:'Total value',value:formatCAD(total),help:returnKnown?'':'Performance data unavailable'},{icon:'trend-up',label:'Total return',value:'—',help:'Cost basis required'},{icon:'portfolio',label:'Number of holdings',value:String(holdings.length),help:''},{icon:'pie-chart',label:'Asset allocation',value:`${assets.length} ${assets.length===1?'ETF':'ETFs'}`,help:''}] as {icon:AppIconName;label:string;value:string;help:string}[]).map(k=><article key={k.label} className="grid h-[108px] grid-cols-[56px_minmax(0,1fr)] items-start gap-4 rounded-[14px] border border-[var(--border)] bg-white p-4 shadow-[var(--shadow-card)]"><span className="grid h-14 w-14 place-items-center rounded-xl bg-blue-50 text-blue-600"><AppIcon name={k.icon} className="h-7 w-7" /></span><div className="grid min-w-0 grid-rows-[20px_30px_16px]"><p className="truncate text-sm leading-5 text-[var(--text-muted)]">{k.label}</p><p className="text-2xl font-bold leading-7 tabular-nums">{k.value}</p><p className="truncate text-xs leading-4 text-[var(--text-muted)]">{k.help || '\u00a0'}</p></div></article>)}</section>
 <section className="mt-3 grid gap-3 xl:grid-cols-[minmax(0,1.4fr)_minmax(300px,.9fr)_270px]"><article className="h-[270px] rounded-[14px] border border-[var(--border)] bg-white p-4 shadow-[var(--shadow-card)]"><header className="flex justify-between"><h2 className="font-bold">Portfolio value</h2><span className="rounded-lg bg-blue-50 px-2 py-1 text-xs font-semibold text-blue-600">Current holdings</span></header><div className="mt-3 h-[205px]">{historical.length === 0 ? <p className="px-4 py-14 text-center text-sm text-[var(--text-muted)]">Historical portfolio balances are not recorded yet. Current value: <strong>{formatCAD(total)}</strong>.</p> : <ResponsiveContainer width="100%" height="100%"><ComposedChart data={historical} margin={{top:8,right:2,left:-15,bottom:0}}><defs><linearGradient id="portfolioFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2563EB" stopOpacity=".2"/><stop offset="1" stopColor="#2563EB" stopOpacity=".02"/></linearGradient></defs><CartesianGrid stroke="#E2E8F0"/><XAxis dataKey="year" tick={{fontSize:10,fill:'#64748B'}} tickLine={false}/><YAxis tickFormatter={v=>v===0?'$0':`$${Math.round(v/1000)}K`} tick={{fontSize:10,fill:'#64748B'}} tickLine={false}/><Tooltip formatter={v=>formatCAD(Number(v))}/><Area type="monotone" dataKey="value" stroke="#2563EB" strokeWidth={2.5} fill="url(#portfolioFill)" isAnimationActive={false}/></ComposedChart></ResponsiveContainer>}</div></article>
 <article className="h-[270px] rounded-[14px] border border-[var(--border)] bg-white p-4 shadow-[var(--shadow-card)]"><h2 className="font-bold">Asset allocation</h2>{total > 0?<div className="mt-4 flex items-center gap-4"><div className="grid h-40 w-40 shrink-0 place-items-center rounded-full" style={{background:`conic-gradient(${assets.map((a,i)=>`${a.color} ${assets.slice(0,i).reduce((s,x)=>s+x.value/total*100,0)}% ${assets.slice(0,i+1).reduce((s,x)=>s+x.value/total*100,0)}%`).join(',')}`}}><div className="grid h-24 w-24 place-items-center rounded-full bg-white text-center"><b className="text-lg">{formatCAD(total)}</b><span className="-mt-4 text-xs text-[var(--text-muted)]">Total</span></div></div><ul className="min-w-0 space-y-3">{assets.map(a=><li key={a.key} className="flex items-center gap-2 text-xs"><i className="h-3 w-3 rounded-full" style={{background:a.color}}/><b className="truncate">{a.key}</b><span className="ml-auto">{formatPct(a.value/total)}</span><span>{formatCAD(a.value)}</span></li>)}</ul></div>:<p className="mt-16 text-center text-sm text-[var(--text-muted)]">Add holdings to see allocation.</p>}</article>
 <aside className="space-y-3"><div className="flex h-[134px] flex-col items-center justify-center rounded-[14px] bg-blue-50 p-4 text-center"><AppIcon name="leaf" className="h-7 w-7 text-blue-600" /><h2 className="mt-2 text-sm font-bold">Your portfolio</h2><p className="mt-1 text-xs text-[var(--text-muted)]">Keep investing to stay on track.</p></div><div className="rounded-[14px] border border-[var(--border)] bg-white p-3"><h2 className="font-bold text-sm">Quick actions</h2><div className="mt-2 grid grid-cols-2 gap-2"><button onClick={openHoldings} className="flex items-center justify-center gap-1 rounded-lg bg-blue-50 p-2 text-xs font-semibold text-blue-600"><AppIcon name="plus" className="h-3.5 w-3.5" />Add holding</button><Link href="/accounts" className="rounded-lg bg-blue-50 p-2 text-center text-xs font-semibold text-blue-600">View accounts</Link></div></div></aside></section>
 <section className="mt-3 rounded-[14px] border border-[var(--border)] bg-white p-4 shadow-[var(--shadow-card)]"><div className="flex justify-between"><h2 className="font-bold">Holdings</h2><button onClick={openHoldings} className="inline-flex items-center gap-1 rounded-lg bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-600"><AppIcon name="plus" className="h-3.5 w-3.5" />Add holding</button></div><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-blue-50/70 text-[var(--text-muted)]"><tr>{['Name','Ticker','Account','Units','Current value','Allocation'].map(x=><th key={x} className="px-3 py-2">{x}</th>)}</tr></thead><tbody>{holdings.map(h=><tr key={h.id} className="border-b border-[var(--border)]"><td className="px-3 py-3 font-semibold">{h.name}</td><td className="px-3 py-3">{h.ticker}</td><td className="px-3 py-3">{h.account}</td><td className="px-3 py-3">{h.units}</td><td className="px-3 py-3 font-semibold">{formatCAD(value(h))}</td><td className="px-3 py-3">{total?formatPct(value(h)/total):'—'}</td></tr>)}</tbody></table></div></section>
 <section className="mt-3"><article className="rounded-[14px] border border-[var(--border)] bg-white p-4 shadow-[var(--shadow-card)]"><header className="flex justify-between"><h2 className="font-bold">Recent activity</h2><Link href="/accounts" className="text-xs font-semibold text-blue-600">View all</Link></header><ul className="mt-2 divide-y divide-[var(--border)]">{activity.length?activity.map(a=><li key={a.id} className="flex justify-between py-2 text-xs"><span>{a.date} · {a.account} contribution</span><b className="text-emerald-600">+{formatCAD(a.amount)}</b></li>):<li className="py-8 text-center text-sm text-[var(--text-muted)]">No contributions yet.</li>}</ul></article></section>
 {manage&&<div id="holding-editor" className="mt-3"><HoldingsForm userId={userId} instruments={instruments} holdings={holdings} quotes={quotes} onChanged={(next)=>{setHoldings(next);setManage(false)}}/></div>}</div>;
}
