'use client';

import { useMemo, useState } from 'react';
import { Card } from '@/components/ui/card';
import { ProjectionChart } from '@/components/projection-chart';
import { formatCAD } from '@/lib/format';
import { futureValue, projectSeries, type ContributionFrequency, type ProjectionInput } from '@/lib/engine/projection';
import type { InstrumentRow } from '@/lib/db/queries';

type HistoryPoint = { date: string; close: number };
type Selection = { ticker: string; pct: number };
const horizons = [5, 10, 20, 30];

function Title({ children }: { children: React.ReactNode }) { return <h2 className="text-base font-semibold tracking-tight">{children}</h2>; }

export function ProjectionsClient({ initialMonthly, initialStarting }: { instruments: InstrumentRow[]; initialTicker: string; initialPoints: HistoryPoint[]; initialMonthly: number; initialStarting: number; accountMonthly: { TFSA: number; RRSP: number }; accountRooms: { TFSA: number; RRSP: number }; cashMonthly: number; selections: Selection[] }) {
  const [monthly, setMonthly] = useState(String(Math.round(initialMonthly)));
  const [annualReturn, setAnnualReturn] = useState('7');
  const [period, setPeriod] = useState('10');
  const [exportMessage, setExportMessage] = useState('');
  const contribution = Number.isFinite(Number(monthly)) ? Math.max(0, Number(monthly)) : 0;
  const rate = Number(annualReturn) || 0;
  const years = Number(period) || 10;
  const input: ProjectionInput = useMemo(() => ({ starting: initialStarting, monthlyContribution: contribution, annualReturn: rate / 100, contributionFrequency: 'monthly' as ContributionFrequency }), [initialStarting, contribution, rate]);
  const series = useMemo(() => projectSeries(input, years * 12), [input, years]);
  const selected = futureValue(input, years);
  const growth = Math.max(0, selected.value - selected.contributed);
  const rows = horizons.map((horizon) => { const row = futureValue(input, horizon); return { horizon, value: row.value, contributed: row.contributed, growth: Math.max(0, row.value - row.contributed) }; });
  const scenarios = [{ label: 'Optimistic scenario', scenarioRate: Math.min(12, rate + 2), tone: 'emerald', icon: '↑' }, { label: 'Base case (current)', scenarioRate: rate, tone: 'blue', icon: '→' }, { label: 'Conservative scenario', scenarioRate: Math.max(0, rate - 2), tone: 'rose', icon: '↓' }].map((scenario) => ({ ...scenario, value: futureValue({ ...input, annualReturn: scenario.scenarioRate / 100 }, years).value }));
  const milestones = [100000, 250000, 500000].map((target) => ({ target, hit: projectSeries(input, 360).find((point) => point.value >= target) }));
  const contributionPct = selected.value > 0 ? selected.contributed / selected.value * 100 : 0;
  const ring = `conic-gradient(#69aefa 0 ${contributionPct}%, #2563eb ${contributionPct}% 100%)`;
  const focusAssumptions = () => { document.getElementById('projection-monthly')?.focus(); document.getElementById('projection-monthly')?.scrollIntoView({ block: 'center', behavior: 'smooth' }); };
  const exportCsv = () => {
    const csv = ['Month,Portfolio value CAD,Starting balance and contributions CAD,Growth CAD', ...series.map(p => `${p.month},${p.value.toFixed(2)},${p.contributed.toFixed(2)},${(p.value-p.contributed).toFixed(2)}`)].join('\r\n');
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' }));
    const link = document.createElement('a'); link.href = url; link.download = 'portfolio-projection.csv'; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000);
    setExportMessage('CSV exported.');
  };
  const copyProjection = async () => {
    const summary = `Portfolio projection: ${formatCAD(initialStarting)} starting value, ${formatCAD(contribution)}/month, ${rate}% annual return, ${years} years. Estimated value ${formatCAD(selected.value)}. Estimate, not a guaranteed return.`;
    try { await navigator.clipboard.writeText(summary); setExportMessage('Projection summary copied.'); } catch { setExportMessage(summary); }
  };

  return <div className="mt-3 space-y-3 pb-8">
    <section className="grid gap-3 xl:grid-cols-[1.05fr_1.35fr_1.15fr]">
      <Card className="!p-4 sm:!p-5"><p className="text-sm text-[var(--text-muted)]">Estimated value ({years} years)</p><p className="mt-1 text-[34px] font-bold leading-none tracking-tight tabular-nums">{formatCAD(selected.value)}</p><div className="mt-4 grid grid-cols-2 divide-x divide-[var(--border)] text-sm"><div><p className="font-bold tabular-nums">{formatCAD(selected.contributed)}</p><p className="mt-1 text-[var(--text-muted)]">Your contributions</p></div><div className="pl-5"><p className="font-bold tabular-nums">{formatCAD(growth)}</p><p className="mt-1 text-[var(--text-muted)]">Investment growth</p></div></div></Card>
      <Card className="!p-4 sm:!p-5"><div className="grid gap-x-5 gap-y-3 sm:grid-cols-2"><label className="text-xs font-medium text-[var(--text-muted)]">Monthly contribution<input id="projection-monthly" aria-label="Monthly contribution" type="number" min="0" value={monthly} onChange={(event) => setMonthly(event.target.value)} className="mt-1 block h-9 w-full rounded-lg border border-[var(--border)] bg-white px-3 text-sm font-semibold text-[var(--text-primary)]" /></label><label className="text-xs font-medium text-[var(--text-muted)]">Expected annual return<span className="mt-1 flex items-center gap-3"><b className="text-sm text-[var(--text-primary)]">{rate}%</b><input aria-label="Expected annual return" type="range" min="0" max="12" step="0.5" value={annualReturn} onChange={(event) => setAnnualReturn(event.target.value)} className="h-2 flex-1 accent-blue-600" /></span></label><label className="text-xs font-medium text-[var(--text-muted)]">Time horizon<select aria-label="Time horizon" value={period} onChange={(event) => setPeriod(event.target.value)} className="mt-1 block h-9 w-full rounded-lg border border-[var(--border)] bg-white px-3 text-sm font-semibold text-[var(--text-primary)]">{horizons.map((item) => <option key={item} value={item}>{item} years</option>)}</select></label><label className="text-xs font-medium text-[var(--text-muted)]">Currency<span className="mt-1 flex h-9 items-center rounded-lg border border-[var(--border)] px-3 text-sm font-semibold text-[var(--text-primary)]">CAD (Canadian Dollar)</span></label></div></Card>
      <section className="flex items-center gap-4 rounded-[var(--radius-card)] border border-emerald-100 bg-gradient-to-r from-emerald-50 to-cyan-50 p-5"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-full bg-emerald-100 text-2xl text-emerald-600">🏆</span><div><p className="font-semibold text-emerald-700">Projection estimate</p><p className="mt-1 text-sm leading-5 text-[var(--text-body)]">At your current pace, you could reach {formatCAD(selected.value)} in {years} years.</p></div></section>
    </section>

    <p className="text-xs text-[var(--text-muted)]">Contribution totals include your starting portfolio balance. These are illustrative scenarios, not guaranteed returns or contribution-room checks.</p>
    <section className="grid gap-3 xl:grid-cols-[1.6fr_1fr]">
      <Card className="!p-4 sm:!p-5"><div className="flex flex-wrap items-center justify-between gap-3"><Title>Projected portfolio value</Title><div className="flex gap-5 text-xs text-[var(--text-muted)]"><span className="flex items-center gap-2"><i className="h-0.5 w-5 bg-blue-600" />Portfolio value</span><span className="flex items-center gap-2"><i className="h-0.5 w-5 border-t-2 border-dashed border-blue-600" />Contributions</span></div></div><div className="mt-2 h-[195px]"><ProjectionChart data={series} /></div></Card>
      <Card className="!p-4 sm:!p-5"><Title>Projection breakdown</Title><table className="mt-3 w-full text-left text-xs"><thead className="bg-slate-50 text-[var(--text-muted)]"><tr><th className="rounded-l px-2 py-2 font-medium">Horizon</th><th className="px-2 py-2 font-medium">Portfolio value</th><th className="px-2 py-2 font-medium">Contributions</th><th className="rounded-r px-2 py-2 text-right font-medium">Growth</th></tr></thead><tbody>{rows.map((row) => <tr key={row.horizon} className={row.horizon === years ? 'bg-blue-50' : 'border-b border-[var(--border)]'}><td className="px-2 py-2 font-medium">{row.horizon} years</td><td className="px-2 py-2 font-semibold">{formatCAD(row.value)}</td><td className="px-2 py-2">{formatCAD(row.contributed)}</td><td className="px-2 py-2 text-right font-semibold">{formatCAD(row.growth)}</td></tr>)}</tbody></table></Card>
    </section>

    <section className="grid gap-3 xl:grid-cols-3">
      <Card className="!p-4 xl:h-[218px]"><Title>Growth composition ({years} years)</Title><div className="mt-3 flex items-center gap-5"><div className="grid h-[128px] w-[128px] shrink-0 place-items-center rounded-full" style={{ background: ring }}><div className="grid h-[84px] w-[84px] place-items-center rounded-full bg-white text-center"><b className="text-sm">{formatCAD(selected.value)}</b><small className="text-[10px] text-[var(--text-muted)]">Total value</small></div></div><div className="space-y-3 text-sm"><div><p className="flex items-center gap-2 text-[var(--text-muted)]"><i className="h-3 w-3 rounded-full bg-[#69aefa]" />Contributions</p><b className="mt-1 block">{formatCAD(selected.contributed)}</b><small className="text-[var(--text-muted)]">{contributionPct.toFixed(1)}%</small></div><div><p className="flex items-center gap-2 text-[var(--text-muted)]"><i className="h-3 w-3 rounded-full bg-blue-600" />Investment growth</p><b className="mt-1 block">{formatCAD(growth)}</b><small className="text-[var(--text-muted)]">{(selected.value > 0 ? 100 - contributionPct : 0).toFixed(1)}%</small></div></div></div></Card>
      <Card className="!p-4 xl:h-[218px]"><Title>Portfolio value over time</Title><div className="mt-3 flex h-[112px] items-end gap-2 border-b border-l border-[var(--border)] px-3 pt-3">{Array.from({ length: 10 }, (_, index) => { const point = series[Math.min(series.length - 1, Math.round((index + 1) / 10 * (series.length - 1)))]; const height = selected.value > 0 ? Math.max(0, point.value / selected.value * 100) : 0; return <div key={index} className="flex h-full flex-1 items-end"><span className="flex w-full flex-col overflow-hidden rounded-t-sm" style={{ height: `${height}%` }}><span className="bg-blue-600" style={{ height: `${point.value > 0 ? Math.max(0, 1-point.contributed/point.value)*100 : 0}%` }} /><span className="bg-[#69aefa]" style={{ height: `${point.value > 0 ? Math.min(1, point.contributed/point.value)*100 : 0}%` }} /></span></div>; })}</div><div className="mt-2 flex justify-between text-xs text-[var(--text-muted)]"><span>Now</span>{[.2,.4,.6,.8].map(fraction => <span key={fraction}>{(years * fraction).toFixed(0)}y</span>)}<span>{years}y</span></div><div className="mt-3 flex justify-center gap-5 text-xs text-[var(--text-muted)]"><span className="flex items-center gap-2"><i className="h-3 w-3 rounded-full bg-[#69aefa]" />Contributions</span><span className="flex items-center gap-2"><i className="h-3 w-3 rounded-full bg-blue-600" />Growth</span></div></Card>
      <Card className="!p-4 xl:h-[218px]"><Title>What if?</Title><div className="mt-3 space-y-3">{scenarios.map((scenario) => <div key={scenario.label} className="grid grid-cols-[34px_1fr_auto] items-center gap-3"><span className={`grid h-9 w-9 place-items-center rounded-full text-lg ${scenario.tone === 'emerald' ? 'bg-emerald-50 text-emerald-600' : scenario.tone === 'rose' ? 'bg-rose-50 text-rose-500' : 'bg-blue-50 text-blue-600'}`}>{scenario.icon}</span><div><p className="text-xs font-medium">{scenario.label}<span className="ml-3 text-[var(--text-muted)]">{scenario.scenarioRate}% return</span></p><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><i className={`block h-full rounded-full ${scenario.tone === 'emerald' ? 'bg-emerald-500' : scenario.tone === 'rose' ? 'bg-rose-500' : 'bg-blue-600'}`} style={{ width: `${Math.min(100, Math.max(0, scenarios[0].value > 0 ? scenario.value / scenarios[0].value * 100 : 0))}%` }} /></div></div><b className="text-sm tabular-nums">{formatCAD(scenario.value)}</b></div>)}</div></Card>
    </section>

    <section className="grid gap-3 xl:grid-cols-[1.55fr_1fr_.7fr]">
      <Card className="!p-4 sm:!p-5"><div className="flex items-center justify-between"><div><h2 id="milestones" className="text-base font-semibold">Milestones</h2><p className="mt-1 text-xs text-[var(--text-muted)]">Forecast thresholds based on your current plan.</p></div><button type="button" onClick={focusAssumptions} className="rounded-lg border border-blue-200 bg-blue-50 px-3 py-2 text-xs font-semibold text-blue-600">Projection assumptions</button></div><table className="mt-3 w-full text-left text-xs"><thead className="bg-slate-50 text-[var(--text-muted)]"><tr><th className="px-2 py-2 font-medium">Milestone</th><th className="px-2 py-2 font-medium">Target value</th><th className="px-2 py-2 font-medium">Estimated year</th></tr></thead><tbody>{milestones.map((milestone) => <tr key={milestone.target} className="border-b border-[var(--border)]"><td className="px-2 py-2.5 font-medium">Reach {formatCAD(milestone.target)}</td><td className="px-2 py-2.5">{formatCAD(milestone.target)}</td><td className="px-2 py-2.5">{milestone.hit ? milestone.hit.month === 0 ? 'Already reached' : `~ ${Math.ceil(milestone.hit.month / 12)} years` : 'Beyond 30 years'}</td></tr>)}</tbody></table></Card>
      <section className="rounded-[var(--radius-card)] border border-blue-100 bg-gradient-to-br from-blue-50 to-sky-50 p-5"><div className="flex items-center justify-between"><Title>Tips to improve your projection</Title></div><div className="mt-3 space-y-2">{['Increase your monthly contribution', 'Consider a higher allocation to growth assets', 'Take advantage of registered accounts', 'Stay consistent over the long term'].map((tip) => <div key={tip} className="flex items-center justify-between rounded-lg bg-white/80 px-3 py-2 text-xs"><span><i className="mr-2 text-emerald-500">✓</i>{tip}</span></div>)}</div></section>
      <Card className="!p-4 sm:!p-5"><Title>Export & share</Title><p className="mt-1 text-xs text-[var(--text-muted)]">Save or share your projections.</p><p role="status" className="mt-2 text-xs text-blue-700">{exportMessage}</p><div className="mt-3 space-y-2">{['Print / save PDF', 'Export data (CSV)', 'Copy projection summary'].map((label, index) => <button key={label} type="button" onClick={index === 0 ? () => window.print() : index === 1 ? exportCsv : copyProjection} className="flex w-full items-center justify-between rounded-lg border border-[var(--border)] px-3 py-2.5 text-xs font-medium"><span>{label}</span><span>›</span></button>)}</div></Card>
    </section>
    <details className="mt-5 rounded-[var(--radius-card)] border border-[var(--border)] bg-white p-4"><summary className="cursor-pointer text-sm font-semibold">Advanced projection tools</summary><div className="mt-3 grid gap-3 text-sm text-[var(--text-muted)] sm:grid-cols-3"><p>Starting portfolio uses the current holdings value: <b className="text-[var(--text-primary)]">{formatCAD(initialStarting)}</b>.</p><p>Monthly plan contribution: <b className="text-[var(--text-primary)]">{formatCAD(contribution)}</b>.</p><p>Account-room and backtest tools remain available for a future focused workflow.</p></div></details>
  </div>;
}
