'use client';

import { useMemo, useState } from 'react';
import { Area, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { projectSeries } from '@/lib/engine/projection';
import { formatCAD } from '@/lib/format';

const HORIZONS = [5, 10, 20, 30] as const;

export function DashboardGrowthCard({ startingValue, monthlyContribution }: { startingValue: number; monthlyContribution: number }) {
  const [horizon, setHorizon] = useState<(typeof HORIZONS)[number]>(10);
  const input = useMemo(() => ({ starting: Math.max(0, startingValue), monthlyContribution: Math.max(0, monthlyContribution), annualReturn: 0.07, contributionFrequency: 'monthly' as const }), [startingValue, monthlyContribution]);
  const series = useMemo(() => projectSeries(input, horizon * 12), [input, horizon]);
  const selected = series.at(-1) ?? { value: 0, contributed: 0 };
  const hasData = startingValue > 0 || monthlyContribution > 0;
  const ticks = [...new Set([0, Math.min(24, horizon * 12), Math.min(60, horizon * 12), horizon * 12])];
  const labelForTick = (month: number) => month === 0 ? 'Now' : `${Math.round(month / 12)}y`;

  return <section className="min-h-[358px] rounded-[var(--radius-card)] border border-[var(--border)] bg-[var(--surface-card)] p-5 shadow-[var(--shadow-card)] xl:h-[358px] xl:overflow-hidden">
    <header className="flex items-start justify-between gap-3"><div><h2 className="text-[17px] font-bold text-[var(--text-primary)]">Portfolio growth <span className="font-normal text-[var(--text-muted)]">(projected)</span></h2><p className="mt-1 text-[28px] font-bold leading-tight tabular-nums text-[var(--text-primary)]">{formatCAD(selected.value)}</p><p className="mt-0.5 text-xs text-[var(--text-muted)]">Estimated value in {horizon} years</p></div><label className="shrink-0"><span className="sr-only">Projection horizon</span><select aria-label="Projection horizon" value={horizon} onChange={(event) => setHorizon(Number(event.target.value) as (typeof HORIZONS)[number])} className="rounded-lg border border-[var(--border)] bg-white px-2.5 py-2 text-xs font-semibold text-[var(--text-primary)] shadow-sm">{HORIZONS.map((years) => <option key={years} value={years}>{years} years</option>)}</select></label></header>
    {!hasData ? <p className="mt-10 rounded-xl bg-[var(--surface-page)] px-3 py-8 text-center text-sm text-[var(--text-muted)]">Add holdings or a monthly plan to see an estimate.</p> : <><div className="mt-3 h-[128px]" role="img" aria-label={`Estimated portfolio value and contributions over ${horizon} years`}><ResponsiveContainer width="100%" height="100%"><ComposedChart data={series} margin={{ top: 6, right: 2, left: 0, bottom: 0 }}><defs><linearGradient id="dashboardGrowthFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2563EB" stopOpacity={0.18} /><stop offset="100%" stopColor="#2563EB" stopOpacity={0.02} /></linearGradient></defs><CartesianGrid stroke="#E2E8F0" vertical={false} /><XAxis dataKey="month" ticks={ticks} tickFormatter={labelForTick} tick={{ fontSize: 10, fill: '#64748B' }} tickLine={false} axisLine={false} /><YAxis tickFormatter={(value) => formatCAD(Number(value))} width={54} tick={{ fontSize: 10, fill: '#64748B' }} tickLine={false} axisLine={false} /><Tooltip labelFormatter={(value) => labelForTick(Number(value))} formatter={(value, name) => [formatCAD(Number(value)), name === 'contributed' ? 'Contributions' : 'Portfolio value']} contentStyle={{ borderRadius: 10, border: '1px solid #E2E8F0', boxShadow: '0 8px 24px rgb(15 23 42 / 12%)' }} /><Area type="monotone" dataKey="value" stroke="#2563EB" strokeWidth={2.2} fill="url(#dashboardGrowthFill)" isAnimationActive={false} /><Line type="monotone" dataKey="contributed" stroke="#2563EB" strokeWidth={1.7} strokeDasharray="5 4" dot={false} isAnimationActive={false} /></ComposedChart></ResponsiveContainer></div><div className="mt-1 flex items-center gap-4 text-[11px] text-[var(--text-muted)]"><span className="inline-flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-[var(--color-primary)]" />Portfolio value</span><span className="inline-flex items-center gap-1.5"><span className="w-4 border-t-2 border-dashed border-[var(--color-primary)]" />Contributions</span></div><dl className="mt-3 grid grid-cols-3 divide-x divide-[var(--border)] text-center"><div className="px-1"><dt className="text-[10px] text-[var(--text-muted)]">Your contributions</dt><dd className="mt-1 text-sm font-bold tabular-nums text-[var(--text-primary)]">{formatCAD(selected.contributed)}</dd></div><div className="px-1"><dt className="text-[10px] text-[var(--text-muted)]">Investment growth</dt><dd className="mt-1 text-sm font-bold tabular-nums text-[var(--text-primary)]">{formatCAD(Math.max(0, selected.value - selected.contributed))}</dd></div><div className="px-1"><dt className="text-[10px] text-[var(--text-muted)]">Annual assumption</dt><dd className="mt-1 text-sm font-bold text-[var(--text-primary)]">7%</dd></div></dl></>}
    <p className="mt-2 text-[10px] leading-4 text-[var(--text-muted)]">Estimate only; the 7% annual return assumption can be reviewed in <a href="/projections" className="font-semibold text-[var(--color-primary)] hover:underline">Projections</a>.</p>
  </section>;
}
