'use client';
import * as Popover from '@radix-ui/react-popover';
import { DayPicker } from 'react-day-picker';
import { useMemo, useState } from 'react';
function parseISO(value: string) { if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return undefined; const [y, m, d] = value.split('-').map(Number); return new Date(y, m - 1, d); }
function formatISO(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; }
export function DatePicker({ value, onChange, id, disabled, 'aria-label': ariaLabel, className = '' }: { value: string; onChange: (value: string) => void; id?: string; disabled?: boolean; 'aria-label'?: string; className?: string }) {
  const [open, setOpen] = useState(false); const selected = useMemo(() => parseISO(value), [value]);
  const displayValue = selected ? selected.toLocaleDateString('en-CA', { month: 'short', day: 'numeric', year: 'numeric' }) : '';
  return <Popover.Root open={open} onOpenChange={setOpen}><Popover.Trigger asChild><button id={id} type="button" disabled={disabled} aria-label={ariaLabel} aria-haspopup="dialog" className={`flex w-full items-center justify-between rounded-xl border border-[var(--line)] bg-[var(--surface)] px-3 py-2 text-left text-sm text-[var(--ink)] shadow-[0_1px_2px_rgba(53,48,36,0.03)] hover:border-[#c8c0b3] focus:border-[#78a9ca] focus:outline-none focus:ring-2 focus:ring-[#dcecf7] disabled:cursor-not-allowed disabled:opacity-60 ${className}`}><span>{displayValue || 'Choose a date'}</span><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" className="h-4 w-4 shrink-0 text-[var(--muted)]"><rect x="3.5" y="5" width="17" height="16" rx="2" /><path d="M8 3.5v3M16 3.5v3M3.5 10h17" /></svg></button></Popover.Trigger><Popover.Portal><Popover.Content sideOffset={6} align="start" collisionPadding={12} className="z-50 rounded-xl border border-[var(--line)] bg-[var(--surface)] p-3 text-[var(--ink)] shadow-[0_12px_30px_rgba(53,48,36,0.14)]"><DayPicker mode="single" selected={selected} defaultMonth={selected} onSelect={(day) => { if (day) { onChange(formatISO(day)); setOpen(false); } }} showOutsideDays classNames={{ months: 'flex', month: 'space-y-3', month_caption: 'flex items-center justify-center text-sm font-semibold', nav: 'flex items-center justify-between', button_previous: 'rounded-md p-1 hover:bg-[#f0eee8]', button_next: 'rounded-md p-1 hover:bg-[#f0eee8]', month_grid: 'w-full border-collapse', weekdays: 'flex', weekday: 'w-9 text-center text-xs text-[var(--muted)]', week: 'mt-1 flex w-full', day: 'h-9 w-9 text-center text-sm', day_button: 'h-9 w-9 rounded-lg hover:bg-[#f0eee8]', selected: 'bg-[#dcecf7] font-semibold text-[#17344a]', today: 'font-semibold text-[var(--accent)]', outside: 'text-[var(--muted)] opacity-50' }} /></Popover.Content></Popover.Portal></Popover.Root>;
}
