'use client';

import { useEffect, useMemo, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Field } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/select';
import { clientSupabase } from '@/lib/supabase/client';
import { deleteHolding, upsertHolding, type HoldingWithInstrument, type InstrumentRow } from '@/lib/db/queries';
import { formatCAD, formatUSD } from '@/lib/format';

type Quote = { price: number; currency: string; asOf?: string };
type SearchResult = { ticker: string; name: string };
type Draft = { id?: number; instrument_id: number; account: 'TFSA' | 'RRSP' | 'CASH'; units: string; balance_native: string; fx_provider: string; fx_rate: string };
const emptyDraft = (instrumentId: number): Draft => ({ instrument_id: instrumentId, account: 'TFSA', units: '', balance_native: '', fx_provider: 'TD', fx_rate: '1' });

function valueFor(h: HoldingWithInstrument, quote?: Quote) { const price = quote?.price ?? 1; const native = h.units * price; return h.currency === 'USD' ? native * h.fx_rate : native; }

export function HoldingsForm({ userId, instruments: initialInstruments, holdings: initialHoldings, quotes: initialQuotes, onChanged }: { userId: string; instruments: InstrumentRow[]; holdings: HoldingWithInstrument[]; quotes: Record<string, Quote>; onChanged: (h: HoldingWithInstrument[]) => void }) {
  const [instruments, setInstruments] = useState(initialInstruments);
  const [holdings, setHoldings] = useState(initialHoldings);
  const [quotes, setQuotes] = useState(initialQuotes);
  const [draft, setDraft] = useState<Draft | null>(null);
  const [search, setSearch] = useState('');
  const [results, setResults] = useState<SearchResult[]>([]);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const selectedInstrument = useMemo(() => instruments.find((i) => i.id === draft?.instrument_id), [instruments, draft]);

  useEffect(() => { const q = search.trim(); if (!q) { setResults([]); return; } const timer = setTimeout(() => fetch(`/api/market/search?q=${encodeURIComponent(q)}`).then((r) => r.ok ? r.json() : null).then((d) => setResults(d?.results ?? [])).catch(() => setResults([])), 250); return () => clearTimeout(timer); }, [search]);
  useEffect(() => { const tickers = [...new Set(holdings.map((h) => h.ticker).filter(Boolean))]; if (!tickers.length) return; const refresh = () => fetch(`/api/market/quotes?tickers=${tickers.join(',')}`).then((r) => r.ok ? r.json() : null).then((d) => { if (d?.quotes) setQuotes(d.quotes); }).catch(() => undefined); const timer = setInterval(refresh, 60000); return () => clearInterval(timer); }, [holdings]);

  function updateLocal(next: HoldingWithInstrument[]) { setHoldings(next); onChanged(next); }
  function chooseInstrument(id: number) { setDraft((d) => d ? { ...d, instrument_id: id, fx_rate: instruments.find((i) => i.id === id)?.currency === 'USD' ? '1.36' : '1' } : d); setSearch(''); setResults([]); }
  async function chooseSearch(r: SearchResult) { const existing = instruments.find((i) => i.ticker === r.ticker); if (existing) return chooseInstrument(existing.id); setBusy(true); try { const res = await fetch('/api/market/instruments', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ticker: r.ticker, name: r.name, currency: r.ticker.endsWith('.TO') || r.ticker.endsWith('.CN') ? 'CAD' : 'USD' }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setInstruments((all) => [...all, data.instrument]); chooseInstrument(data.instrument.id); } catch (e) { setMessage(e instanceof Error ? e.message : 'Could not add instrument'); } finally { setBusy(false); } }
  function edit(h: HoldingWithInstrument) { setDraft({ id: h.id, instrument_id: h.instrument_id, account: h.account as Draft['account'], units: String(h.units), balance_native: String(h.balance_native), fx_provider: h.fx_provider, fx_rate: String(h.fx_rate) }); }
  async function save(e: React.FormEvent) { e.preventDefault(); if (!draft) return; setBusy(true); setMessage(null); try { const instrument = instruments.find((i) => i.id === draft.instrument_id); if (!instrument) throw new Error('Choose an instrument'); const fields = { instrument_id: draft.instrument_id, account: draft.account, units: Number(draft.units) || 0, balance_native: Number(draft.balance_native) || 0, fx_provider: draft.fx_provider, fx_rate: Number(draft.fx_rate) || 1 }; await upsertHolding(clientSupabase(), userId, draft.id ? { ...fields, id: draft.id } : fields); const next: HoldingWithInstrument[] = draft.id ? holdings.map((h) => h.id === draft.id ? { ...h, ...fields, ticker: instrument.ticker, name: instrument.name, currency: instrument.currency } : h) : [...holdings, { ...fields, id: Math.max(0, ...holdings.map((h) => h.id)) + 1, ticker: instrument.ticker, name: instrument.name, currency: instrument.currency }]; updateLocal(next); setDraft(null); } catch (e) { setMessage(e instanceof Error ? e.message : 'Could not save holding'); } finally { setBusy(false); } }
  async function remove(h: HoldingWithInstrument) { if (!window.confirm(`Delete ${h.ticker} holding?`)) return; setBusy(true); try { await deleteHolding(clientSupabase(), userId, h.id); updateLocal(holdings.filter((x) => x.id !== h.id)); if (draft?.id === h.id) setDraft(null); } catch (e) { setMessage(e instanceof Error ? e.message : 'Could not delete holding'); } finally { setBusy(false); } }

  return <div className="space-y-6"><Card title="Holdings" description="Track units and see live market values. Quotes refresh every 60 seconds."><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-zinc-200 text-xs uppercase tracking-wide text-zinc-500 dark:border-zinc-800"><tr><th className="pb-2">Instrument</th><th className="pb-2">Account</th><th className="pb-2">Units</th><th className="pb-2">Native value</th><th className="pb-2">Live CAD value</th><th className="pb-2">Actions</th></tr></thead><tbody>{holdings.map((h) => <tr key={h.id} className="border-b border-zinc-100 dark:border-zinc-900"><td className="py-3"><div className="font-medium">{h.ticker}</div><div className="text-xs text-zinc-500">{h.name}</div></td><td>{h.account}</td><td className="tabular-nums">{h.units.toLocaleString()}</td><td className="tabular-nums">{h.currency === 'USD' ? formatUSD(h.balance_native) : formatCAD(h.balance_native)}</td><td className="tabular-nums">{formatCAD(valueFor(h, quotes[h.ticker]))}</td><td><div className="flex gap-2"><Button variant="secondary" onClick={() => edit(h)}>Edit</Button><Button variant="danger" onClick={() => remove(h)} disabled={busy}>Delete</Button></div></td></tr>)}</tbody></table>{holdings.length === 0 && <p className="py-8 text-center text-sm text-zinc-500">No holdings yet. Add your first ETF below.</p>}</div></Card>
    <Card title={draft?.id ? 'Edit holding' : 'Add holding'}>{message && <p className="mb-3 rounded-md bg-red-50 p-2 text-sm text-red-700 dark:bg-red-950/30 dark:text-red-300">{message}</p>}<form onSubmit={save} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Instrument"><div className="relative"><Input value={search || selectedInstrument?.ticker || ''} onChange={(e) => { setSearch(e.target.value); if (!draft) setDraft(emptyDraft(instruments[0]?.id ?? 0)); }} placeholder="Search ticker…" required />{results.length > 0 && <div className="absolute z-10 mt-1 w-full rounded-md border border-zinc-200 bg-white shadow-lg dark:border-zinc-700 dark:bg-zinc-900">{results.map((r) => <button type="button" key={r.ticker} className="block w-full px-3 py-2 text-left text-sm hover:bg-zinc-100 dark:hover:bg-zinc-800" onClick={() => chooseSearch(r)} disabled={busy}><span className="font-medium">{r.ticker}</span><span className="ml-2 text-zinc-500">{r.name}</span></button>)}</div>}</div></Field><Field label="Account"><Select value={draft?.account ?? 'TFSA'} onChange={(e) => setDraft((d) => ({ ...(d ?? emptyDraft(instruments[0]?.id ?? 0)), account: e.target.value as Draft['account'] }))}><option>TFSA</option><option>RRSP</option><option>CASH</option></Select></Field><Field label="Units"><Input type="number" min="0" step="0.0001" value={draft?.units ?? ''} onChange={(e) => setDraft((d) => ({ ...(d ?? emptyDraft(instruments[0]?.id ?? 0)), units: e.target.value }))} required /></Field><Field label="Balance (native)" hint="Optional cost/balance reference"><Input type="number" min="0" step="0.01" value={draft?.balance_native ?? ''} onChange={(e) => setDraft((d) => ({ ...(d ?? emptyDraft(instruments[0]?.id ?? 0)), balance_native: e.target.value }))} /></Field>{selectedInstrument?.currency === 'USD' && <><Field label="FX provider"><Select value={draft?.fx_provider ?? 'TD'} onChange={(e) => setDraft((d) => ({ ...(d ?? emptyDraft(instruments[0]?.id ?? 0)), fx_provider: e.target.value }))}><option value="TD">TD</option><option value="WEALTHSIMPLE">Wealthsimple</option><option value="CUSTOM">Custom</option></Select></Field><Field label="FX rate (CAD/USD)"><Input type="number" min="0" step="0.000001" value={draft?.fx_rate ?? '1.36'} onChange={(e) => setDraft((d) => ({ ...(d ?? emptyDraft(instruments[0]?.id ?? 0)), fx_rate: e.target.value }))} /></Field></>}<div className="flex items-end gap-2"><Button type="submit" disabled={busy || !draft?.instrument_id}>{draft?.id ? 'Save changes' : 'Add holding'}</Button>{draft?.id && <Button variant="secondary" onClick={() => setDraft(null)}>Cancel</Button>}</div></form></Card></div>;
}
